[package]
name = "mongodb_test"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = { version = "0.3", features = ["compat"] }
async-recursion = "1.1.1"
tokio = { version = "1", features = ["full"] }